# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f8014f05d38936f05a3e83cbe8eff0611ec46d543262887f151e1189c6532beb76a6849c7e06d94cad2e90bd548ce99ac6b005390370efcb352144046e6c9bd8

test:
  secret_key_base: f5ae9125734af77bf1bdffb76e2abd4b86aca271cbd9ec5a85c48168f4c8fb344b7dec1be942d24351bb24a22eb06cdaf0fb4db67e15966c096f0186b2538bad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
